/**
 * POST /api/compare
 *
 * Compares two places with live data. Called by the Compare page client.
 * Returns: { a: { reading, forecast }, b: { reading, forecast }, report: string }
 *
 * The "report" is generated by Groq (qwen/qwen3-32b) and is profile-tailored.
 * Falls back to a deterministic template if Groq is unavailable or fails.
 *
 * Cross-state guard: both places must be in the same state (Maharashtra in v1).
 */

import { NextRequest, NextResponse } from 'next/server';
import { getAqiReading, getForecastResult, getStations } from '../../../lib/db';

export const runtime = 'nodejs';  // not edge -- we call Groq which is fine on either but nodejs keeps fetch simpler

interface CompareBody {
  placeA: string;   // station id e.g. "MUMBAI_BORIVALI"
  placeB: string;
  profile?: 'healthy' | 'child' | 'elderly' | 'asthmatic';
}

export async function POST(req: NextRequest) {
  let body: CompareBody;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'invalid JSON body' }, { status: 400 });
  }

  if (!body.placeA || !body.placeB) {
    return NextResponse.json({ error: 'placeA and placeB are required' }, { status: 400 });
  }
  if (body.placeA === body.placeB) {
    return NextResponse.json({ error: 'placeA and placeB must be different' }, { status: 400 });
  }

  const profile = body.profile ?? 'healthy';

  // Fetch stored readings (and forecasts when they exist). Retry once on a dropped connection.
  let stationA, stationB, readingA, readingB, forecastA, forecastB;
  let dataError: unknown = null;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      [stationA, stationB, readingA, readingB, forecastA, forecastB] = await Promise.all([
        getStation(body.placeA),
        getStation(body.placeB),
        getAqiReading(body.placeA),
        getAqiReading(body.placeB),
        getForecastResult(body.placeA),
        getForecastResult(body.placeB),
      ]);
      dataError = null;
      break;
    } catch (e) {
      dataError = e;
    }
  }
  if (dataError) {
    console.error('[api/compare] data layer failed:', dataError);
    return NextResponse.json({
      a: null,
      b: null,
      report: 'Comparison unavailable — the comparison service is offline. Try again in a few minutes.',
      profile,
      offline: true,
    }, { status: 200 });
  }

  if (!stationA || !stationB) {
    return NextResponse.json({ error: 'unknown station id' }, { status: 400 });
  }

  // Cross-state guard
  if (stationA.state !== stationB.state) {
    return NextResponse.json(
      { error: `cross-state comparison not supported in v1: '${stationA.state}' vs '${stationB.state}'. Pick two Maharashtra stations.` },
      { status: 400 },
    );
  }

  const emptyForecast = { r_squared: 0, model_version: 'stored-readings', points: [] as { date: string; predicted_aqi: number; confidence_low: number; confidence_high: number }[] };
  if (!forecastA) forecastA = emptyForecast;
  if (!forecastB) forecastB = emptyForecast;

  if (!readingA || !readingB) {
    return NextResponse.json({
      a: { station: stationA, reading: readingA, forecast: forecastA },
      b: { station: stationB, reading: readingB, forecast: forecastB },
      report: 'Comparison unavailable — stored readings are missing for one of the selected areas.',
      profile,
      offline: true,
    }, { status: 200 });
  }

  // Generate the Groq report (or fall back to template)
  let report: string;
  try {
    report = await generateGroqReport({
      placeA: { ...stationA, reading: readingA, forecast: forecastA },
      placeB: { ...stationB, reading: readingB, forecast: forecastB },
      profile,
    });
  } catch (e) {
    console.error('[api/compare] Groq failed, falling back to template:', e);
    report = generateTemplateReport({
      placeA: { ...stationA, reading: readingA, forecast: forecastA },
      placeB: { ...stationB, reading: readingB, forecast: forecastB },
      profile,
    });
  }

  return NextResponse.json({
    a: {
      station: stationA,
      reading: readingA,
      forecast: forecastA,
    },
    b: {
      station: stationB,
      reading: readingB,
      forecast: forecastB,
    },
    report,
    profile,
  });
}

async function getStation(id: string) {
  const stations = await getStations('Maharashtra');
  return stations.find(s => s.id === id) ?? null;
}

interface GroqContext {
  placeA: { name: string; city: string; state: string; reading: { aqi: number; bucket: string; pm25: number; pm10: number; no2: number; so2: number; co: number; o3: number; dominant: string }; forecast: { r_squared: number; model_version: string; points: { date: string; predicted_aqi: number; confidence_low: number; confidence_high: number }[] } };
  placeB: { name: string; city: string; state: string; reading: { aqi: number; bucket: string; pm25: number; pm10: number; no2: number; so2: number; co: number; o3: number; dominant: string }; forecast: { r_squared: number; model_version: string; points: { date: string; predicted_aqi: number; confidence_low: number; confidence_high: number }[] } };
  profile: string;
}

function num(value: number | null | undefined, digits: number): string {
  return Number.isFinite(value) ? (value as number).toFixed(digits) : 'n/a';
}

function peakAqi(points: { predicted_aqi: number }[]): string {
  if (!points.length) return 'not available';
  return String(Math.max(...points.map(p => p.predicted_aqi)));
}

async function generateGroqReport(ctx: GroqContext): Promise<string> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) throw new Error('GROQ_API_KEY not set');

  const prompt = `You are a clear, factual air-quality reporter. Compare these two Maharashtra places for a user whose health profile is "${ctx.profile}". Use only the numbers below. If a forecast is missing, say so and compare the stored readings.

Place A: ${ctx.placeA.name}, ${ctx.placeA.city}
- Current AQI: ${ctx.placeA.reading.aqi} (${ctx.placeA.reading.bucket})
- Pollutants (µg/m³ except CO): PM2.5=${num(ctx.placeA.reading.pm25, 0)}, PM10=${num(ctx.placeA.reading.pm10, 0)}, NO2=${num(ctx.placeA.reading.no2, 0)}, SO2=${num(ctx.placeA.reading.so2, 0)}, CO=${num(ctx.placeA.reading.co, 2)}, O3=${num(ctx.placeA.reading.o3, 0)}
- Dominant pollutant: ${ctx.placeA.reading.dominant}
- 7-day forecast peak: ${peakAqi(ctx.placeA.forecast.points)}
- Model: ${ctx.placeA.forecast.model_version} (R²=${num(ctx.placeA.forecast.r_squared, 2)})

Place B: ${ctx.placeB.name}, ${ctx.placeB.city}
- Current AQI: ${ctx.placeB.reading.aqi} (${ctx.placeB.reading.bucket})
- Pollutants (µg/m³ except CO): PM2.5=${num(ctx.placeB.reading.pm25, 0)}, PM10=${num(ctx.placeB.reading.pm10, 0)}, NO2=${num(ctx.placeB.reading.no2, 0)}, SO2=${num(ctx.placeB.reading.so2, 0)}, CO=${num(ctx.placeB.reading.co, 2)}, O3=${num(ctx.placeB.reading.o3, 0)}
- Dominant pollutant: ${ctx.placeB.reading.dominant}
- 7-day forecast peak: ${peakAqi(ctx.placeB.forecast.points)}
- Model: ${ctx.placeB.forecast.model_version} (R²=${num(ctx.placeB.forecast.r_squared, 2)})

Write 2 short paragraphs (max 180 words total) of plain English:
1. Which place has cleaner air RIGHT NOW and why (mention the dominant pollutant on each side).
2. Which is better for the next 7 days for a ${ctx.profile}, and what to do in the worse one.

No emojis, no markdown headings, no bullet points.`;

  const models = [
    process.env.GROQ_PRIMARY_MODEL ?? 'openai/gpt-oss-20b',
    process.env.GROQ_FALLBACK_MODEL ?? 'openai/gpt-oss-120b',
  ];
  let lastError = 'Groq returned no text';
  for (const model of models) {
    const r = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3,
        max_tokens: 800,
      }),
    });
    if (!r.ok) {
      lastError = `Groq HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`;
      continue;
    }
    const data = await r.json();
    const message = data.choices?.[0]?.message;
    const text = (message?.content || message?.reasoning || '').trim();
    if (text) return text;
    lastError = `Groq model ${model} returned an empty comparison`;
  }
  throw new Error(lastError);
}

function generateTemplateReport(ctx: GroqContext): string {
  const aCleaner = ctx.placeA.reading.aqi <= ctx.placeB.reading.aqi;
  const clean = aCleaner ? ctx.placeA : ctx.placeB;
  const dirty = aCleaner ? ctx.placeB : ctx.placeA;
  return `${clean.name} (${clean.reading.aqi}, ${clean.reading.bucket}) has cleaner air than ${dirty.name} (${dirty.reading.aqi}, ${dirty.reading.bucket}). The dominant pollutant at the cleaner place is ${clean.reading.dominant}; at the worse place it's ${dirty.reading.dominant}.

For a ${ctx.profile}, the cleaner place is the better choice today. If you have to be at the worse place, limit outdoor exertion and consider an N95 mask. The 7-day forecast suggests ${clean.name} will stay the better option for the next few days.`;
}